server:
  port: 8080
spring:
  application:
    name: shiftFlow-platform

logging:
  level:
    com:
      shiftFlow: DEBUG
  pattern:
    console: d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

